services:
  ag-keycloak:
    build:
      context: ./ag-keycloak
      dockerfile: Dockerfile
    container_name: ag-keycloak-frontend
    ports:
      - "9019:80"

  next-keycloak:
    build:
      context: ./next-keycloak
      dockerfile: Dockerfile
    container_name: next-keycloak-frontend
    env_file:
      - ./next-keycloak/.env
    ports:
      - "9020:3000"
